name: Robustness_test_dependencies
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - dowhy=0.11.1
  - ipython=8.18.1
  - matplotlib=3.8.4
  - numpy=1.23.2
  - pandas=1.5.3
  - scikit-learn=1.5.0
  - scipy=1.13.0
  - sympy=1.12
  - tqdm=4.66.4
  - ipywidgets
